#############################################################################
# Makefile for building: Thesis
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Thesis.pro
# Template: app
# Command: /opt/qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile Thesis.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I../RVO2-3D -I../lua -I../../NGL/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore -Imoc -I. -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Thesis1.0.0
DISTDIR = /home/i7902033/RVO2NGL/ThesisEnhancements/obj/Thesis1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt/5.5/gcc_64 -Wl,-rpath,/home/i7902033/RVO2NGL/ThesisEnhancements/L/home/i7902033/NGL/lib -Wl,-rpath,/home/i7902033/NGL/lib -Wl,-rpath,/opt/qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -L/home/i7902033/NGL/lib -l NGL -ltiff -llua-5.1 -L/opt/qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Flock.cpp \
		src/LuaFunctions.cpp \
		src/LuaGetSet.cpp \
		src/LuaInterpreter.cpp \
		src/main.cpp \
		src/NGLScene.cpp \
		src/Obstacle3D.cpp \
		src/UserInterface.cpp \
		src/RVO2-3D/Agent.cpp \
		src/RVO2-3D/KdTree.cpp \
		src/RVO2-3D/RVOSimulator.cpp \
		FileLoad.cpp moc/moc_NGLScene.cpp \
		moc/moc_UserInterface.cpp \
		moc/moc_FileLoad.cpp
OBJECTS       = obj/Flock.o \
		obj/LuaFunctions.o \
		obj/LuaGetSet.o \
		obj/LuaInterpreter.o \
		obj/main.o \
		obj/NGLScene.o \
		obj/Obstacle3D.o \
		obj/UserInterface.o \
		obj/Agent.o \
		obj/KdTree.o \
		obj/RVOSimulator.o \
		obj/FileLoad.o \
		obj/moc_NGLScene.o \
		obj/moc_UserInterface.o \
		obj/moc_FileLoad.o
DIST          = *.lua \
		*.qss \
		../../NGL/UseNGL.pri \
		Thesis.pro include/Flock.h \
		include/LuaInterpreter.h \
		include/LuaVector3.h \
		include/NGLScene.h \
		include/Obstacle3D.h \
		include/OpenGlInterface.h \
		include/UserInterface.h \
		include/kaguya.hpp \
		include/lua.hpp \
		include/LuaCustomTypes.hpp \
		include/LuaFunctions.hpp \
		include/LuaGetSet.hpp \
		include/luawrapper.hpp \
		include/luawrapperutil.hpp \
		include/RVO2-3D/Agent.h \
		include/RVO2-3D/API.h \
		include/RVO2-3D/Definitions.h \
		include/RVO2-3D/KdTree.h \
		include/RVO2-3D/RVO.h \
		include/RVO2-3D/RVOSimulator.h \
		include/RVO2-3D/Vector3.h \
		include/lua/lauxlib.h \
		include/lua/lua.h \
		include/lua/luaconf.h \
		include/lua/lualib.h \
		FileLoad.h \
		include/OpenGlInterface.h src/Flock.cpp \
		src/LuaFunctions.cpp \
		src/LuaGetSet.cpp \
		src/LuaInterpreter.cpp \
		src/main.cpp \
		src/NGLScene.cpp \
		src/Obstacle3D.cpp \
		src/UserInterface.cpp \
		src/RVO2-3D/Agent.cpp \
		src/RVO2-3D/KdTree.cpp \
		src/RVO2-3D/RVOSimulator.cpp \
		FileLoad.cpp
QMAKE_TARGET  = Thesis
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Thesis


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_UserInterface.h ui_FileLoad.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Thesis.pro ../../.qmake.cache /opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../.qmake.cache \
		/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../NGL/UseNGL.pri \
		/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf \
		Thesis.pro \
		/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/opt/qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Thesis.pro
/opt/qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt/5.5/gcc_64/mkspecs/common/unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/linux.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../.qmake.cache:
/opt/qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
../../NGL/UseNGL.pri:
/opt/qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/c++11.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/qt.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/resources.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/moc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/uic.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/opt/qt/5.5/gcc_64/mkspecs/features/lex.prf:
Thesis.pro:
/opt/qt/5.5/gcc_64/lib/libQt5OpenGL.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Gui.prl:
/opt/qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Thesis.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/Flock.h include/LuaInterpreter.h include/LuaVector3.h include/NGLScene.h include/Obstacle3D.h include/OpenGlInterface.h include/UserInterface.h include/kaguya.hpp include/lua.hpp include/LuaCustomTypes.hpp include/LuaFunctions.hpp include/LuaGetSet.hpp include/luawrapper.hpp include/luawrapperutil.hpp include/RVO2-3D/Agent.h include/RVO2-3D/API.h include/RVO2-3D/Definitions.h include/RVO2-3D/KdTree.h include/RVO2-3D/RVO.h include/RVO2-3D/RVOSimulator.h include/RVO2-3D/Vector3.h include/lua/lauxlib.h include/lua/lua.h include/lua/luaconf.h include/lua/lualib.h FileLoad.h include/OpenGlInterface.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Flock.cpp src/LuaFunctions.cpp src/LuaGetSet.cpp src/LuaInterpreter.cpp src/main.cpp src/NGLScene.cpp src/Obstacle3D.cpp src/UserInterface.cpp src/RVO2-3D/Agent.cpp src/RVO2-3D/KdTree.cpp src/RVO2-3D/RVOSimulator.cpp FileLoad.cpp $(DISTDIR)/
	$(COPY_FILE) --parents UserInterface.ui FileLoad.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_NGLScene.cpp moc/moc_UserInterface.cpp moc/moc_FileLoad.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_NGLScene.cpp moc/moc_UserInterface.cpp moc/moc_FileLoad.cpp
moc/moc_NGLScene.cpp: ../../NGL/include/ngl/Camera.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../NGL/include/ngl/Vec4.h \
		../../NGL/include/ngl/Vec2.h \
		../../NGL/include/ngl/Vec3.h \
		../../NGL/include/ngl/Mat4.h \
		../../NGL/include/ngl/RibExport.h \
		../../NGL/include/ngl/Plane.h \
		../../NGL/include/ngl/AABB.h \
		../../NGL/include/ngl/BBox.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Colour.h \
		../../NGL/include/ngl/Light.h \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		../../NGL/include/ngl/Text.h \
		../../NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		../../NGL/include/ngl/VAOFactory.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/QResizeEvent \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QOpenGLWidget \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		include/NGLScene.h
	/opt/qt/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/i7902033/RVO2NGL/ThesisEnhancements -I/home/i7902033/RVO2NGL/ThesisEnhancements/include -I/home/i7902033/RVO2NGL/RVO2-3D -I/home/i7902033/RVO2NGL/lua -I/home/i7902033/NGL/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore include/NGLScene.h -o moc/moc_NGLScene.cpp

moc/moc_UserInterface.cpp: /opt/qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		include/NGLScene.h \
		../../NGL/include/ngl/Camera.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../NGL/include/ngl/Vec4.h \
		../../NGL/include/ngl/Vec2.h \
		../../NGL/include/ngl/Vec3.h \
		../../NGL/include/ngl/Mat4.h \
		../../NGL/include/ngl/RibExport.h \
		../../NGL/include/ngl/Plane.h \
		../../NGL/include/ngl/AABB.h \
		../../NGL/include/ngl/BBox.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Colour.h \
		../../NGL/include/ngl/Light.h \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		../../NGL/include/ngl/Text.h \
		../../NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		../../NGL/include/ngl/VAOFactory.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/QResizeEvent \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QOpenGLWidget \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		include/UserInterface.h
	/opt/qt/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/i7902033/RVO2NGL/ThesisEnhancements -I/home/i7902033/RVO2NGL/ThesisEnhancements/include -I/home/i7902033/RVO2NGL/RVO2-3D -I/home/i7902033/RVO2NGL/lua -I/home/i7902033/NGL/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore include/UserInterface.h -o moc/moc_UserInterface.cpp

moc/moc_FileLoad.cpp: /opt/qt/5.5/gcc_64/include/QtWidgets/QDialog \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		FileLoad.h
	/opt/qt/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/i7902033/RVO2NGL/ThesisEnhancements -I/home/i7902033/RVO2NGL/ThesisEnhancements/include -I/home/i7902033/RVO2NGL/RVO2-3D -I/home/i7902033/RVO2NGL/lua -I/home/i7902033/NGL/include -I/opt/qt/5.5/gcc_64/include -I/opt/qt/5.5/gcc_64/include/QtOpenGL -I/opt/qt/5.5/gcc_64/include/QtWidgets -I/opt/qt/5.5/gcc_64/include/QtGui -I/opt/qt/5.5/gcc_64/include/QtCore FileLoad.h -o moc/moc_FileLoad.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_UserInterface.h ui_FileLoad.h
compiler_uic_clean:
	-$(DEL_FILE) ui_UserInterface.h ui_FileLoad.h
ui_UserInterface.h: UserInterface.ui
	/opt/qt/5.5/gcc_64/bin/uic UserInterface.ui -o ui_UserInterface.h

ui_FileLoad.h: FileLoad.ui
	/opt/qt/5.5/gcc_64/bin/uic FileLoad.ui -o ui_FileLoad.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/Flock.o: src/Flock.cpp include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		include/LuaFunctions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Flock.o src/Flock.cpp

obj/LuaFunctions.o: src/LuaFunctions.cpp ../lua/lua.h \
		../lua/luaconf.h \
		../lua/lualib.h \
		include/luawrapper.hpp \
		../lua/lauxlib.h \
		include/luawrapperutil.hpp \
		include/LuaCustomTypes.hpp \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/LuaInterpreter.h \
		include/lua.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/LuaFunctions.o src/LuaFunctions.cpp

obj/LuaGetSet.o: src/LuaGetSet.cpp include/LuaGetSet.hpp \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/LuaGetSet.o src/LuaGetSet.cpp

obj/LuaInterpreter.o: src/LuaInterpreter.cpp include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lualib.h \
		../lua/lauxlib.h \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/LuaInterpreter.o src/LuaInterpreter.cpp

obj/main.o: src/main.cpp /opt/qt/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		include/NGLScene.h \
		../../NGL/include/ngl/Camera.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../NGL/include/ngl/Vec4.h \
		../../NGL/include/ngl/Vec2.h \
		../../NGL/include/ngl/Vec3.h \
		../../NGL/include/ngl/Mat4.h \
		../../NGL/include/ngl/RibExport.h \
		../../NGL/include/ngl/Plane.h \
		../../NGL/include/ngl/AABB.h \
		../../NGL/include/ngl/BBox.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Colour.h \
		../../NGL/include/ngl/Light.h \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		../../NGL/include/ngl/Text.h \
		../../NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		../../NGL/include/ngl/VAOFactory.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/QResizeEvent \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QOpenGLWidget \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		include/UserInterface.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/NGLScene.o: src/NGLScene.cpp /opt/qt/5.5/gcc_64/include/QtGui/QMouseEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		include/NGLScene.h \
		../../NGL/include/ngl/Camera.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../NGL/include/ngl/Vec4.h \
		../../NGL/include/ngl/Vec2.h \
		../../NGL/include/ngl/Vec3.h \
		../../NGL/include/ngl/Mat4.h \
		../../NGL/include/ngl/RibExport.h \
		../../NGL/include/ngl/Plane.h \
		../../NGL/include/ngl/AABB.h \
		../../NGL/include/ngl/BBox.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Colour.h \
		../../NGL/include/ngl/Light.h \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		../../NGL/include/ngl/Text.h \
		../../NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		../../NGL/include/ngl/VAOFactory.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/QResizeEvent \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QOpenGLWidget \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		../../NGL/include/ngl/NGLInit.h \
		../../NGL/include/ngl/Singleton.h \
		../../NGL/include/ngl/VAOPrimitives.h \
		../../NGL/include/ngl/Random.h \
		../../NGL/include/ngl/ShaderLib.h \
		../../NGL/include/ngl/Shader.h \
		../../NGL/include/ngl/ShaderProgram.h \
		../../NGL/include/ngl/Util.h \
		../../NGL/include/ngl/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/Obstacle3D.o: src/Obstacle3D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Obstacle3D.o src/Obstacle3D.cpp

obj/UserInterface.o: src/UserInterface.cpp include/UserInterface.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		include/NGLScene.h \
		../../NGL/include/ngl/Camera.h \
		../../NGL/include/ngl/Types.h \
		../../NGL/include/ngl/glew.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		../../NGL/include/ngl/Vec4.h \
		../../NGL/include/ngl/Vec2.h \
		../../NGL/include/ngl/Vec3.h \
		../../NGL/include/ngl/Mat4.h \
		../../NGL/include/ngl/RibExport.h \
		../../NGL/include/ngl/Plane.h \
		../../NGL/include/ngl/AABB.h \
		../../NGL/include/ngl/BBox.h \
		../../NGL/include/ngl/AbstractVAO.h \
		../../NGL/include/ngl/Colour.h \
		../../NGL/include/ngl/Light.h \
		../../NGL/include/ngl/Transformation.h \
		../../NGL/include/ngl/NGLassert.h \
		../../NGL/include/ngl/Text.h \
		../../NGL/include/ngl/VertexArrayObject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QHash \
		/opt/qt/5.5/gcc_64/include/QtGui/QFont \
		../../NGL/include/ngl/VAOFactory.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QEvent \
		/opt/qt/5.5/gcc_64/include/QtGui/QResizeEvent \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QOpenGLWidget \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../RVO2-3D/RVO.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		include/Flock.h \
		include/luawrapper.hpp \
		../lua/lua.h \
		../lua/luaconf.h \
		../lua/lauxlib.h \
		include/LuaInterpreter.h \
		include/lua.hpp \
		../lua/lualib.h \
		ui_UserInterface.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QVariant \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QAction \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qaction.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QDoubleSpinBox \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QGridLayout \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QHeaderView \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QMenuBar \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmenubar.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmenu.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QSpacerItem \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QStatusBar \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qstatusbar.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QToolBar \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtoolbar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QFile \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QFileDialog \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdir.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfileinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QTextStream \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QMessageBox \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QDir \
		FileLoad.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QDialog
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/UserInterface.o src/UserInterface.cpp

obj/Agent.o: src/RVO2-3D/Agent.cpp ../RVO2-3D/Agent.h \
		../RVO2-3D/API.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Vector3.h \
		../RVO2-3D/Definitions.h \
		../RVO2-3D/KdTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Agent.o src/RVO2-3D/Agent.cpp

obj/KdTree.o: src/RVO2-3D/KdTree.cpp ../RVO2-3D/KdTree.h \
		../RVO2-3D/API.h \
		../RVO2-3D/Vector3.h \
		../RVO2-3D/Agent.h \
		../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/Definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/KdTree.o src/RVO2-3D/KdTree.cpp

obj/RVOSimulator.o: src/RVO2-3D/RVOSimulator.cpp ../RVO2-3D/RVOSimulator.h \
		../RVO2-3D/API.h \
		../RVO2-3D/Vector3.h \
		../RVO2-3D/Agent.h \
		../RVO2-3D/KdTree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/RVOSimulator.o src/RVO2-3D/RVOSimulator.cpp

obj/FileLoad.o: FileLoad.cpp FileLoad.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QDialog \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		ui_FileLoad.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QVariant \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QAction \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qaction.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QGridLayout \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QHeaderView \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QTextEdit \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qtextedit.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextdocument.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QFile \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QFileDialog \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qdir.h \
		/opt/qt/5.5/gcc_64/include/QtCore/qfileinfo.h \
		/opt/qt/5.5/gcc_64/include/QtWidgets/QMessageBox \
		/opt/qt/5.5/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/qt/5.5/gcc_64/include/QtCore/QTextStream
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FileLoad.o FileLoad.cpp

obj/moc_NGLScene.o: moc/moc_NGLScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_NGLScene.o moc/moc_NGLScene.cpp

obj/moc_UserInterface.o: moc/moc_UserInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_UserInterface.o moc/moc_UserInterface.cpp

obj/moc_FileLoad.o: moc/moc_FileLoad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_FileLoad.o moc/moc_FileLoad.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

